import { minify } from 'html-minifier'

const options = {
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  collapseWhitespace: true
};


/**
 * @type {import('@wcj/ejs-cli/lib/watch.mjs').Options}
 */
export default {
  watchOption: {

  },
  globelData: {},
  data: {
    "template/about/index.ejs": "./about.json",
    "template/index.ejs": "./data.json",
    "template/home.ejs": {
      "name": "Hello World",
      "age": 362
    }
  },
  beforeSaveHTML: (html, output, filename) => {
    const minHTML = minify(html, options)
    return minHTML + "<!-- Hello -->"
  }
};