name: CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run build
      - run: npm install
      - run: npm run build
        working-directory: examples

      - run: npm install idoc@1 -g
      - name: Create idoc config.
        working-directory: core
        run: |
          cat > idoc.yml << EOF
          site: "EJS Cli {{version}}"
          menus:
            Home: index.html
            Sponsor: https://jaywcjlove.github.io/#/sponsor
          EOF
      - run: idoc -s "EJS Cli {{version}}"
        working-directory: core

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: core/dist/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./core/dist


      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: core/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ steps.create_tag.outputs.version }}
          filter-author: (小弟调调™|Renovate Bot|renovate-bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: package.json info
        uses: jaywcjlove/github-action-package@main
        with:
          path: core/package.json
          unset: scripts,devDependencies

      - run: npm publish --access public --provenance
        continue-on-error: true
        working-directory: core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://jaywcjlove.github.io/#/sponsor) [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@wcj/ejs-cli@${{steps.create_tag.outputs.versionNumber}}/file/README.md)
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/@wcj/ejs-cli/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  

            ```bash
            npm i @wcj/ejs-cli@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.compareurl }}
            
            ${{ steps.changelog.outputs.changelog }}